# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
# SPDX-License-Identifier: MIT

- id: reuse-me
  name: ReuseMe - ReuseMe - License and Copyright validation
  description: Validates your repository against the REUSE specification
  entry: reuse-me
  language: node
