# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
#
# SPDX-License-Identifier: CC0-1.0

name: 'reuse-me'
author: 'Kevin de Jong'
description: >
  Validate the files committed as part of a Pull Request against REUSE compliance.

branding:
  icon: 'code'  
  color: 'white'

inputs:
  token: 
    description: 'GitHub token used to access GitHub (eg. github.token)'
    required: true

runs:
  using: 'node16'
  main: 'lib/action/index.js'
