# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
#
# SPDX-License-Identifier: CC0-1.0

---

name: Validate for REUSE compliance
on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  reuse-me:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-build-deploy/reuse-me@ci/add-basic-ci-validation
        with:
          token: ${{ github.token }}
