# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
#
# SPDX-License-Identifier: CC0-1.0

---

name: Release and Deploy GitHub Action

concurrency: deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: read

jobs:
  github-release:
    name: Create GitHub Release
    outputs:
      next-version: ${{ steps.commisery.outputs.next-version }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate version
        id: commisery
        uses: tomtom-international/commisery-action/bump@v2
        with:
          create-release: true
          token: ${{ github.token }}
          version-prefix: v

  release-action:
    name: Release GitHub Action
    runs-on: ubuntu-latest
    needs: github-release
    if: needs.github-release.outputs.next-version != ''

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.github-release.outputs.next-version }}

      - name: Update the ${{ needs.github-release.outputs.next-version }} tag
        uses: actions/publish-action@v0.2.2
        with:
          source-tag: ${{ needs.github-release.outputs.next-version }}
